name: recordy slow E2E test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.8.0'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install project dependencies
        run: yarn

      - name: Create dev certfile
        run: |
          sudo apt-get update
          sudo apt install libnss3-tools wget
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          sudo cp mkcert-v1.4.3-linux-amd64 /usr/local/bin/mkcert
          sudo chmod +x /usr/local/bin/mkcert
          mkcert -install
          mkcert localhost 127.0.0.1 ::1

      - name: Create envfile
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" > .env
          echo "HTTPS=false" >> .env      

      - name: Create Cypress envfile
        run: |
          echo '{
            "CYPRESS_TEST_EMAIL": ${{ secrets.CYPRESS_TEST_EMAIL }},
            "CYPRESS_TEST_PASSWORD": ${{ secrets.CYPRESS_TEST_PASSWORD }}
          }' > cypress.env.json

      - name: Run app
        run: yarn dev & yarn wait-on http://localhost:3000

      - name: Run cypress
        run: |
          export CYPRESS_PROJECT_ID=${{ secrets.CYPRESS_PROJECT_ID }}
          yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome
